"use client";

import { Alert, Card, Select, Space, Switch, Table, Tag } from "antd";
import type { ColumnsType } from "antd/es/table";
import { useEffect, useMemo, useState } from "react";
import type { ScheduleSeller, ScheduleStore } from "./schedule-workspace";

interface ControlShift { shift_id: string; employee_id: string; employee_full_name: string; store_id: number; store_name: string; starts_at: string; ends_at: string; is_replacement: boolean; matched_photo_report_count: number; has_matched_photo_report: boolean; }
interface UnmatchedReport { feedback_id: string; seller_id: string; seller_full_name: string; report_store_id: number; store_name: string; submitted_at: string; local_date: string; }
interface Props { month: string; stores: ScheduleStore[]; sellers: ScheduleSeller[]; }
function time(iso: string) { return new Intl.DateTimeFormat("uk-UA", { timeZone: "Europe/Kyiv", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(iso)); }

export function SchedulePhotoControl({ month, stores, sellers }: Props) {
  const [shifts, setShifts] = useState<ControlShift[]>([]); const [unmatched, setUnmatched] = useState<UnmatchedReport[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const [storeId, setStoreId] = useState<number | undefined>(); const [sellerId, setSellerId] = useState<string | undefined>(); const [onlyReplacements, setOnlyReplacements] = useState(false);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); void fetch(`/api/admin/network/schedule-photo-control?month=${month}`, { signal: controller.signal }).then(async (response) => { const body = await response.json() as { shifts?: ControlShift[]; unmatched_reports?: UnmatchedReport[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "Не вдалося завантажити контроль"); setShifts(body.shifts ?? []); setUnmatched(body.unmatched_reports ?? []); }).catch((value: unknown) => { if (!controller.signal.aborted) setError(value instanceof Error ? value.message : "Не вдалося завантажити контроль"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [month]);
  const filteredShifts = useMemo(() => shifts.filter((row) => (!storeId || row.store_id === storeId) && (!sellerId || row.employee_id === sellerId) && (!onlyReplacements || row.is_replacement)), [onlyReplacements, sellerId, shifts, storeId]);
  const filteredUnmatched = useMemo(() => unmatched.filter((row) => (!storeId || row.report_store_id === storeId) && (!sellerId || row.seller_id === sellerId)), [sellerId, storeId, unmatched]);
  const shiftColumns: ColumnsType<ControlShift> = [{ title: "Зміна", key: "shift", render: (_, row) => `${row.employee_full_name} · ${row.store_name}` }, { title: "Час", key: "time", render: (_, row) => `${time(row.starts_at)}–${time(row.ends_at)}` }, { title: "Заміна", dataIndex: "is_replacement", render: (value: boolean) => value ? <Tag color="gold">Так</Tag> : "—" }, { title: "Фотозвіт", dataIndex: "matched_photo_report_count", render: (value: number) => value ? <Tag color="green">Є: {value}</Tag> : <Tag color="red">Немає</Tag> }];
  const unmatchedColumns: ColumnsType<UnmatchedReport> = [{ title: "Продавець", dataIndex: "seller_full_name" }, { title: "Магазин", dataIndex: "store_name" }, { title: "Дата і час", dataIndex: "submitted_at", render: time }, { title: "Статус", render: () => <Tag color="orange">Поза зміною</Tag> }];
  return <div className="space-y-4">{error ? <Alert type="warning" showIcon message="Контроль фотозвитів недоступний" description={error} /> : null}<Card><Space wrap size="middle"><Select aria-label="Фільтр магазинів контролю фотозвітів" allowClear placeholder="Усі магазини" value={storeId} onChange={setStoreId} className="min-w-52" options={stores.map((store) => ({ value: store.id, label: store.name }))} /><Select aria-label="Фільтр продавців контролю фотозвітів" allowClear showSearch optionFilterProp="label" placeholder="Усі продавці" value={sellerId} onChange={setSellerId} className="min-w-56" options={sellers.map((seller) => ({ value: seller.id, label: seller.display_label ?? seller.full_name }))} /><span className="inline-flex items-center gap-2 text-sm text-ink-700">Лише заміни<Switch checked={onlyReplacements} onChange={setOnlyReplacements} /></span></Space></Card><Card title={`Планові зміни та фотозвіти · ${filteredShifts.length}`}><Table rowKey="shift_id" loading={loading} columns={shiftColumns} dataSource={filteredShifts} pagination={{ pageSize: 30, hideOnSinglePage: true }} /></Card><Card title={`Фотозвіти поза плановою зміною · ${filteredUnmatched.length}`}><Table rowKey="feedback_id" loading={loading} columns={unmatchedColumns} dataSource={filteredUnmatched} pagination={{ pageSize: 20, hideOnSinglePage: true }} /></Card><Alert type="info" showIcon message="Фотозвіт підтверджує відправлення під PIN, а не повну фактичну явку чи зарплатний час." /></div>;
}
