"use client";

import { DndContext, DragOverlay, KeyboardSensor, MouseSensor, TouchSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { theme as antdTheme, Tooltip } from "antd";
import { useMemo, useState, type CSSProperties, type ReactNode } from "react";
import { isSaturdayOrSunday, kyivDateTimeParts, kyivMonthDates, moveSameDayShiftToKyivDate, ukraineHolidayName } from "@/lib/scheduleTime";
import type { ScheduleSeller, ScheduleStore, Shift } from "./schedule-workspace";

export interface GridMoveRequest { shift: Shift; targetDate: string; targetStoreId: number; startsAt: string; endsAt: string; }
interface Props { stores: ScheduleStore[]; month: string; shifts: Shift[]; sellers: ScheduleSeller[]; readonly: boolean; onRequestMove: (request: GridMoveRequest) => void; onEdit: (shift: Shift) => void; onError: (message: string) => void; }
const dropId = (storeId: number, date: string) => `schedule:${storeId}:${date}`;
const overnight = (shift: Shift) => kyivDateTimeParts(shift.starts_at).date !== kyivDateTimeParts(shift.ends_at).date;
const label = (date: string) => new Intl.DateTimeFormat("uk-UA", { timeZone: "Europe/Kyiv", weekday: "short" }).format(new Date(`${date}T12:00:00Z`)).slice(0, 2);

function ShiftCard({ shift, readonly, onEdit }: { shift: Shift; readonly: boolean; onEdit: (value: Shift) => void }) {
  const { token } = antdTheme.useToken(); const blocked = readonly || overnight(shift);
  const drag = useDraggable({ id: shift.shift_id, data: { shift }, disabled: blocked });
  return <Tooltip title={`${shift.employee_full_name} · ${kyivDateTimeParts(shift.starts_at).time}–${kyivDateTimeParts(shift.ends_at).time}${shift.is_replacement ? " · Заміна" : ""}`}><div ref={drag.setNodeRef} {...drag.attributes} {...drag.listeners} role="button" tabIndex={blocked ? -1 : 0} onDoubleClick={() => !blocked && onEdit(shift)} onKeyDown={(event) => { if (event.key === "Enter" && !blocked) { event.preventDefault(); onEdit(shift); } }} className={`truncate rounded px-1 py-0.5 text-[10px] leading-3 ${blocked ? "cursor-default" : "cursor-grab active:cursor-grabbing"}`} style={{ opacity: drag.isDragging ? 0.35 : 1, background: shift.is_replacement ? token.colorWarningBg : token.colorInfoBg, color: shift.is_replacement ? token.colorWarningText : token.colorInfoText }}>{shift.employee_full_name}</div></Tooltip>;
}

function Cell({ storeId, date, readonly, acceptsActiveShift, style, children }: { storeId: number; date: string; readonly: boolean; acceptsActiveShift: boolean; style: CSSProperties; children: ReactNode }) {
  const { token } = antdTheme.useToken(); const drop = useDroppable({ id: dropId(storeId, date), data: { storeId, date }, disabled: readonly || !acceptsActiveShift });
  return <div ref={drop.setNodeRef} className="min-h-7 border-b border-r p-px transition-colors" style={{ ...style, background: drop.isOver ? token.colorPrimaryBg : style.background, outline: drop.isOver ? `2px solid ${token.colorPrimary}` : undefined, outlineOffset: -2 }}>{children}</div>;
}

export function ScheduleMonthGrid({ stores, month, shifts, sellers, readonly, onRequestMove, onEdit, onError }: Props) {
  const { token } = antdTheme.useToken(); const [active, setActive] = useState<Shift | null>(null);
  const sensors = useSensors(useSensor(MouseSensor, { activationConstraint: { distance: 6 } }), useSensor(TouchSensor, { activationConstraint: { delay: 180, tolerance: 6 } }), useSensor(KeyboardSensor));
  const dates = useMemo(() => kyivMonthDates(month), [month]);
  const sellerById = useMemo(() => new Map(sellers.map((seller) => [seller.id, seller])), [sellers]);
  const cells = useMemo(() => { const result = new Map<string, Shift[]>(); shifts.filter((s) => s.shift_status === "scheduled").forEach((s) => { const key = `${s.store_id}:${kyivDateTimeParts(s.starts_at).date}`; result.set(key, [...(result.get(key) ?? []), s]); }); return result; }, [shifts]);
  const finish = (event: DragEndEvent) => { const shift = (event.active.data.current?.shift ?? active) as Shift | undefined; const target = event.over?.data.current as { storeId?: number; date?: string } | undefined; setActive(null); if (!shift || !target?.storeId || !target.date || readonly || (shift.store_id === target.storeId && kyivDateTimeParts(shift.starts_at).date === target.date)) return; try { const next = moveSameDayShiftToKyivDate(shift.starts_at, shift.ends_at, target.date); onRequestMove({ shift, targetStoreId: target.storeId, targetDate: target.date, startsAt: next.starts_at, endsAt: next.ends_at }); } catch (error) { onError(error instanceof Error ? error.message : "Не вдалося підготувати перенесення"); } };
  const acceptsActiveShift = (storeId: number) => !active || (() => { const seller = sellerById.get(active.employee_id); return seller?.store_id === storeId || seller?.replacement_store_ids.includes(storeId) || false; })();
  const header = { background: token.colorFillTertiary, borderColor: token.colorBorderSecondary, color: token.colorTextSecondary }; const regular = { background: token.colorBgContainer, borderColor: token.colorBorderSecondary }; const saturday = { background: token.colorInfoBg, borderColor: token.colorBorderSecondary }; const sunday = { background: token.colorFillSecondary, borderColor: token.colorBorderSecondary }; const holiday = { background: token.colorErrorBg, borderColor: token.colorErrorBorder, color: token.colorErrorText };
  return <DndContext sensors={sensors} onDragStart={(e) => setActive(e.active.data.current?.shift as Shift ?? null)} onDragCancel={() => setActive(null)} onDragEnd={finish}><div className="overflow-x-auto rounded-lg" style={{ border: `1px solid ${token.colorBorderSecondary}` }}><div className="min-w-[980px] xl:min-w-0"><div className="grid" style={{ gridTemplateColumns: `76px repeat(${stores.length}, minmax(0, 1fr))` }}><div className="sticky left-0 top-0 z-30 border-b border-r px-1 py-1 text-[10px] font-medium" style={header}>Дата</div>{stores.map((s) => <Tooltip key={s.id} title={s.name}><div className="sticky top-0 z-20 truncate border-b border-r px-1 py-1 text-center text-[10px] font-medium" style={header}>{s.name}</div></Tooltip>)}{dates.map((date) => { const holidayName = ukraineHolidayName(date); const dow = new Date(`${date}T12:00:00Z`).getUTCDay(); const style = holidayName ? holiday : dow === 6 ? saturday : dow === 0 ? sunday : regular; return <div key={date} className="contents"><Tooltip title={holidayName ?? (isSaturdayOrSunday(date) ? "Календарний вихідний — мережа працює" : undefined)}><div className="sticky left-0 z-10 border-b border-r px-1 py-1 text-[10px] font-medium" style={style}><div>{date.slice(-2)}.{date.slice(5, 7)}</div><div className="text-[9px] font-normal opacity-75">{holidayName ? "свято" : label(date)}</div></div></Tooltip>{stores.map((store) => { const rows = cells.get(`${store.id}:${date}`) ?? []; return <Cell key={store.id} storeId={store.id} date={date} readonly={readonly} acceptsActiveShift={acceptsActiveShift(store.id)} style={style}>{rows.slice(0, 1).map((shift) => <ShiftCard key={shift.shift_id} shift={shift} readonly={readonly} onEdit={onEdit} />)}{rows.length > 1 ? <Tooltip title={rows.slice(1).map((s) => s.employee_full_name).join(", ")}><div className="truncate px-1 text-[9px]" style={{ color: token.colorTextSecondary }}>+{rows.length - 1}</div></Tooltip> : null}</Cell>; })}</div>; })}</div></div></div><DragOverlay dropAnimation={null}>{active ? <div className="max-w-40 truncate rounded px-2 py-1 text-xs shadow" style={{ background: active.is_replacement ? token.colorWarningBg : token.colorInfoBg, color: active.is_replacement ? token.colorWarningText : token.colorInfoText }}>{active.employee_full_name}</div> : null}</DragOverlay></DndContext>;
}
